### ISSUE TITLE
Inference/finetuning 

### ISSUE THREAD

**Issue by Tahsin-Mayeesha** [csebuetnlp/BanglaNLG#1]
When will the inference code and finetuning scripts for banglanlg will be released? If not finetuning then whats the prompts for nmt or Summarization etc? @abhik1505040

**Comment by abhik1505040** [comment]
Hi, @Tahsin-Mayeesha , we plan to release the finetuning script and models by the following week. We don't use multi-task learning (with the fine-tuning datasets) during pretraining, so there is no need for prefix codes/prompts during finetuning/inference.

**Comment by abhik1505040** [comment]
Hi, we have added the required scripts in the repo, please feel free to reopen this issue if you have any questions.
